08-01-23 13:20 ERROR <urlopen error [Errno 11001] getaddrinfo failed> while connecting to: http://diveintopyhon.org/
08-01-23 13:20 ERROR HTTP Error 403: Forbidden while connecting to: https://realpython.com/python-f-strings/
08-01-23 13:21 ERROR unknown url type: 'ww.asdf.com' while connecting to: ww.asdf.com
